### PR TITLE
Fix negation behaviour of output param in config

### LINKED ISSUE #54: output option is negated in config per presedence of hard coded switch option.
The regression is happening because we're specifying output twice, once here : 

https://github.com/starbelly/rebar3_ex_doc/blob/026741dba8a3524232709ca87eb7b4b3c2098d8e/src/rebar3_ex_doc.erl#L207

The switch will take precedence over what's in rebar.config. We need to omit the switch if it's in config. We also need to give a healthy warning if both are specified, specifically if `--output foo` (not the default directory) is defined and the output option is also defined in rebar.config. 

Tests should be added.

### PR DESCRIPTION
**Pull request by starbelly**
Closes #54

### CODE REVIEW

File: src/rebar3_ex_doc.erl [hunk 1]
```diff
@@ -39,7 +39,7 @@ init(State) ->
                 {app, $a, "app", string, help(app)},
                 {ex_doc, $e, "ex_doc", string, help(ex_doc)},
                 {canonical, $n, "canonical", string, help(canonical)},
-                {output, $o, "output", {string, ?DEFAULT_DOC_DIR}, help(output)},
+                {output, $o, "output", {atom, undefined}, help(output)},
```
Comment (starbelly) [inline src/rebar3_ex_doc.erl:42]: Don't like this as it effects the help output, but having it set to doc by default makes the decision logic for output tricky.

Comment (starbelly) [reply src/rebar3_ex_doc.erl]: I resolved this via replacing the value in opts with `undefined` if `output == doc`. A little odd, but I think it's fine.
